// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuFg_mDdI1RQ6unYPtM5-cM5XoPTfNT0s',
    appId: '1:732365774876:android:fb64719689de0cb7bf3fd9',
    messagingSenderId: '732365774876',
    projectId: 'med-safe-invictus-2025',
    storageBucket: 'med-safe-invictus-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkvKHBN0f9q_6C07KICzt91_AFTILR10Q',
    appId: '1:732365774876:ios:7369fb4853bd8ef9bf3fd9',
    messagingSenderId: '732365774876',
    projectId: 'med-safe-invictus-2025',
    storageBucket: 'med-safe-invictus-2025.firebasestorage.app',
    iosBundleId: 'com.example.medApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqlnVSMUTmIkshmBC-uLHjWsPT69FoWns',
    appId: '1:732365774876:web:c93d01f4e443c84ebf3fd9',
    messagingSenderId: '732365774876',
    projectId: 'med-safe-invictus-2025',
    authDomain: 'med-safe-invictus-2025.firebaseapp.com',
    storageBucket: 'med-safe-invictus-2025.firebasestorage.app',
    measurementId: 'G-PTDGNXMRNM',
  );

}